// Generated by scripts/generate-tracker-database.mjs from trackerProvenance.json.
// Do not edit this runtime-only file directly; run `npm run data:generate`.
import type { TrackerRule } from "../shared/types.ts";

export const TRACKER_DATABASE: readonly TrackerRule[] = [
  {"id":"google-ads-doubleclick","domain":"doubleclick.net","company":"Google","category":"advertising"},
  {"id":"google-ads-services","domain":"googleadservices.com","company":"Google","category":"advertising"},
  {"id":"google-ads-syndication","domain":"googlesyndication.com","company":"Google","category":"advertising"},
  {"id":"clarity","domain":"clarity.ms","company":"Microsoft","category":"analytics"},
  {"id":"google-analytics","domain":"google-analytics.com","company":"Google","category":"analytics"},
  {"id":"linkedin-insight","domain":"snap.licdn.com","company":"LinkedIn","category":"social"},
  {"id":"adobe-audience-manager","domain":"demdex.net","company":"Adobe","category":"other"},
] as const;
